ignored:
  - SC1091   # Non-interactive shell sourcing (virtualenv activate)
  - DL3008   # Pin versions not strictly needed for small base image
  - DL3013   # Using pip without requirements.txt is intentional
  - DL3015   # --no-install-recommends already minimizes
  - DL3042   # Cleanup handled manually

failure-threshold: warning